services:
  yaas:
    platform: linux/arm64
    container_name: yaas
    build:
      context: .
    volumes:
      - ./build/bin:/app/bin
      - ./build/db:/app/db
      - ./build/html/public:/app/html/public
    ports:
      - "127.0.0.1:13000:80"
    environment:
      SERVER_ADDRESS: "0.0.0.0:80"
      DATABASE_DIR: "/app/db/env"
      HTTPS: "0"
      FRONTEND_DIR: "/app/html"
      CAPTCHA_SITE_KEY: "xxx"
      CAPTCHA_API_KEY: "xxx"
      JWT_SECRET: "secret"
    networks:
      - yaasnet
    restart: always

networks:
  yaasnet:
    name: yaasnet
