CREATE TABLE org_members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    roles VARCHAR(255) NOT NULL,
    status VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_org_members_org FOREIGN KEY (org_id) REFERENCES orgs(id),
    CONSTRAINT fk_org_members_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_org_members_org_id ON org_members(org_id);
CREATE INDEX idx_org_members_user_id ON org_members(user_id);
CREATE UNIQUE INDEX idx_org_members_org_id_user_id ON org_members(org_id, user_id);
