CREATE TABLE users (
    id CHAR(36) PRIMARY KEY,
    email VARCHAR(250) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
