CREATE TABLE passwords (
    id CHAR(36) PRIMARY KEY,
    password VARCHAR(250) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TRIGGER trigger_update_updated_at
BEFORE UPDATE ON passwords
FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_column();
