CREATE TABLE orgs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(10) NOT NULL,
    owner_id INTEGER NULL DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,
    CONSTRAINT fk_orgs_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE INDEX idx_orgs_owner_id ON orgs(owner_id);
CREATE INDEX idx_orgs_deleted_at ON orgs(deleted_at);
